main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('story1/', views.story1, name='story1'),
    path('story3/', views.story3, name='story3'),
    path('bonus/', views.bonus, name='bonus'),
]

matkul/urls.py
from django.urls import path

from . import views

app_name = 'matkul'

urlpatterns = [
    path('', views.matkulView, name='matkul'),
    path('create', views.matkulCreate, name='create'),
    path('delete/<str:key>', views.delete, name='delete'),
    path('details/<str:key>', views.details, name='details'),
]

story3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('matkul/', include('matkul.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

story6/urls.py
from django.urls import path

from .views import index

app_name = 'story6'

urlpatterns = [
    path('', index, name='story6_index'),
]

story7/urls.py
from django.urls import path

from .views import index

app_name = 'story7'

urlpatterns = [
    path('', index, name='story7_index'),
]

story8/urls.py
from django.urls import path

from .views import index, search

app_name = 'story8'

urlpatterns = [
    path('', index, name='story8_index'),
    path('data/', search, name='story8_data'),
]

story9/urls.py
from django.urls import path

from .views import index, user_login, user_logout, user_signup

app_name = 'story9'

urlpatterns = [
    path('', index, name='index'),
    path('signup/', user_signup, name='signup'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
]

main/models.py
from django.db import models

# Create your models here.

matkul/models.py
from django.db import models

# Create your models here.
class MataKuliah(models.Model):
    kode = models.CharField(max_length=10)
    nama = models.CharField(max_length=50)
    dosen = models.CharField(max_length=50)
    sks = models.PositiveIntegerField(default=0)
    deskripsi = models.CharField(max_length=1000)

    def __str__(self):
        return self.nama

story6/models.py
from django.db import models

# Create your models here.
class Aktivitas(models.Model):
    nama = models.CharField(max_length=50, default="")

class Peserta(models.Model):
    nama = models.CharField(max_length=50, default="")
    aktivitas = models.ForeignKey(Aktivitas, on_delete=models.CASCADE)

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

matkul/forms.py
from django import forms

from .models import MataKuliah

class MataKuliahCreateForm(forms.ModelForm):
    class Meta:
        model = MataKuliah
        fields = '__all__'
        widgets = {
            'kode' : forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'CSGE601020',
            }),
            'nama' : forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Dasar-dasar Pemrograman 1',
            }),
            'dosen' : forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Drs. Lim Yohanes Stefanus M.Math., Ph.D.',
            }),
            'sks' : forms.NumberInput(attrs={
                'class': 'form-control',
            }),
            'deskripsi' : forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Mata Kuliah Wajib Fakultas',
            }),
        }

story6/forms.py
from django import forms

from .models import Aktivitas, Peserta

class AktifitasForm(forms.ModelForm):
    class Meta:
        model = Aktivitas
        fields = '__all__'
        widgets = {
            'nama' : forms.TextInput(attrs={
                'class' : 'form-control',
                'placeholder' : 'Masukkan nama kegiatan'
            })
        }

class PesertaForm(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = '__all__'
        widgets = {
            'nama' : forms.TextInput(attrs={
                'class' : 'form-control',
                'placeholder' : 'Tambahkan peserta'
            })
        }

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

def story1(request):
    return render(request, 'main/story1.html')

def story3(request):
    return render(request, 'main/story3.html')

def bonus(request):
    return render(request, 'main/bonus.html')

matkul/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import MataKuliah
from .forms import MataKuliahCreateForm


def matkulView(request):
    allMatkul = MataKuliah.objects.all()
    context = {'allMatkul': allMatkul}
    return render(request, 'matkul/matkul.html', context)

def matkulCreate(request):
    form = MataKuliahCreateForm(request.POST or None)
    if(form.is_valid() and request.method == 'POST'):
        form.save()
    
    context = {'form': form}
    return render(request, 'matkul/matkul_create.html', context)

def details(request, key):
    matkul = MataKuliah.objects.get(id=key)
    context = {'matkul': matkul}
    return render(request, 'matkul/matkul_details.html', context)

def delete(request, key):
    matkul = MataKuliah.objects.get(id=key)
    matkul.delete()
    return redirect('/matkul')

story6/views.py
from django.shortcuts import render
from .models import Aktivitas, Peserta
from .forms import AktifitasForm, PesertaForm

# Create your views here.
def index(request):
    return render(request, 'story6/index.html')

def tambah_aktivitas(request):
    pass

def hapus_aktivitas(request):
    pass

def tambah_peserta(request):
    pass

def hapus_peserta(request):
    pass

story7/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story7/index.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

# Create your views here.
def index(request):
    return render(request, 'story8/index.html')

def search(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    ret = requests.get(url)
    data = json.loads(ret.content)
    return JsonResponse(data, safe=False)

story9/views.py
from django.shortcuts import render, redirect, resolve_url
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

# Create your views here.
def index(request):
    return render(request, 'story9/index.html')

def user_signup(request):
    if (not request.user.is_anonymous):
        return redirect(resolve_url('story9:index'))

    context = {
        'error': False
    }

    if (request.method == "POST"):
        user = None
        try:
            user = User.objects.get(username = request.POST['username'])
        except:
            user == None

        if(user == None):
            new_user = User.objects.create_user(request.POST['username'], '', request.POST['password'])
            new_user.save()
            login(request, new_user)
            return redirect(resolve_url('story9:index'))
        else:
            context['error'] = True
            return render(request, 'story9/signup.html', context)

    return render(request, 'story9/signup.html', context)

def user_login(request):
    if (request.user.is_authenticated):
        return redirect(resolve_url('story9:index'))

    context = {
        'error': False
    }

    if (request.method == "POST"):
        user = authenticate(
            username = request.POST['username'],
            password = request.POST['password'],
        )

        if (user == None):
            context['error'] = True
            return render(request, 'story9/login.html', context)
        else:
            login(request, user)
            return redirect(resolve_url('story9:index'))

    return render(request, 'story9/login.html', context)

def user_logout(request):
    logout(request)
    return redirect(resolve_url('story9:index'))

main/templates/main/bonus.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Bonus</title>
{% endblock meta %}

{% block content %}
<p>Halaman web ini masih dalam masa pengembangan :(</p>
<p>Silakan gunakan fitur yang sudah tersedia :)</p>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 4</title>
{% endblock meta %}

{% block content %}
<div id='title'>
  <h1>Selamat Datang</h1>
  <p>Silakan gunakan navbar di atas untuk melihat-lihat story saya :)</p>
</div>
{% endblock content %}

main/templates/main/story1.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    <title>Story 1</title>
{% endblock meta %}

{% block content %}
    <h1>Profil Saya</h1>

    <img class="prof-pic" src={% static 'img/FR09.jpg' %} alt="foto profil">

    <p>Nama : Anis Farhan Itsnaini</p>
    <p>Tempat Kuliah : Universitas Indonesia, Fakultas Ilmu Komputer</p>
    <p>NPM : 1906285541</p>
    <p>Angkatan : 2019 (Maung)</p>
    <p>Hobi : menunda tugas sampe <i>deadline</i></p>
    <p>Riwayat Pendidikan :</p>

    <table>
        <tr><th>Nama Sekolah</th><th>Tahun</th></tr>
        <tr><td>SD Muhammadiyah Pati</td><td>2007-2013</td></tr>
        <tr><td>SMP N SBBS Sragen</td><td>2013-2016</td></tr>
        <tr><td>SMA Cahaya Rancamaya</td><td>2016-2019</td></tr>
        <tr><td>Universitas Indonesia</td><td>2019-Sekarang</td></tr>
    </table>

    <p>Tentang saya : Saya adalah mahasiswa tahun kedua jurusan Ilmu Komputer Universitas Indonesia yang saat ini sedang mengerjakan tugas mata kuliah Perancangan dan Pemrograman Web</p>
    <br>
    <h3>Media Sosial</h3>
    <h3>
        <a href="https://www.linkedin.com/in/anis-farhan-itsnaini-499014191/">
            <img src={% static 'img/linkedin.jpg' %} alt="LinkedIn">
        </a>
        <a href="https://steamcommunity.com/id/anisfarhanitsnaini">
            <img src={% static 'img/steam.png' %} alt="Steam">
        </a>
        <a href="https://web.facebook.com/farhan.itsnaini.1">
            <img src={% static 'img/facebook.png' %} alt="Facebook">
        </a>
        <a href="https://www.instagram.com/farhansbbs/">
            <img src={% static 'img/instagram.jpg' %} alt="Instagram">
        </a>
    </h3>
{% endblock content %}

main/templates/main/story3.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <link rel="stylesheet" href="{% static 'css/style3.css' %}">
    <title>Story 3</title>
{% endblock meta %}

{% block content %}
    <img id="prof-pic" src={% static 'img/FR09.jpg' %} alt="foto profil">
    <h1>Part time Student, Full-time learner</h1>
    <h1 class="tagline">I love to learn dan discover new things</h1>

    <h2>About me</h2>
    <p>Hello there, it's me Farhan</p>
    <p>Nice to meet you :)</p>
    <br>
    <p style="font-weight: bold;">Educational Background</p>
    <p class="sekolah">SMP</p>
    <p><img src={% static 'img/SBBS.jpg' %} alt="SBBS" class="school-image"></p>
    <p>Sragen Bilingual Boarding School</p>
    <p class="sekolah">SMA</p>
    <p><img src={% static 'img/CRIBS.jpg' %} alt="SBBS" class="school-image"></p>
    <p>Cahaya Rancamaya Islamic Boarding School</p>

    <h2>Contacts</h2>
    <h3>
        <a href="https://www.linkedin.com/in/anis-farhan-itsnaini-499014191/" target="_blank">
            <img src={% static 'img/linkedin.jpg' %} alt="LinkedIn">
        </a>
        <a href="https://web.facebook.com/farhan.itsnaini.1" target="_blank">
            <img src={% static 'img/facebook.png' %} alt="Facebook">
        </a>
    </h3>
    <h3>
        <a href="https://steamcommunity.com/id/anisfarhanitsnaini" target="_blank">
            <img src={% static 'img/steam.png' %} alt="Steam">
        </a>
        <a href="https://www.instagram.com/farhansbbs/" target="_blank">
            <img src={% static 'img/instagram.jpg' %} alt="Instagram">
        </a>
    </h3>
{% endblock content %}

matkul/templates/matkul/matkul.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Mata Kuliah</title>
{% endblock meta %}

{% block content %}
<table>
    <thead>
        <tr>
            <th>Kode</th>
            <th>Nama Mata Kuliah</th>
            <th>Cek Detail</th>
        </tr>
    </thead>
    <tbody>
        {% for matkul in allMatkul %}
            <tr>
                <td>{{matkul.kode}}</td>
                <td>{{matkul.nama}}</td>
                <td><a href="{% url 'matkul:details' matkul.id %}"> deskripsi</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<a href="/matkul/create"><button>Tambah Matkul</button></a>
{% endblock content %}

matkul/templates/matkul/matkul_create.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Buat Matkul Baru</title>
{% endblock meta %}

{% block content %}
<a href="/matkul"><button>Kembali</button></a>
<form method="POST">
    {% csrf_token %}
    <p>Kode: {{form.kode}}</p>
    <p>Nama: {{form.nama}}</p>
    <p>Dosen: {{form.dosen}}</p>
    <p>SKS: {{form.sks}}</p>
    <p>Deskripsi: {{form.deskripsi}}</p>

    <input type="submit" value="Submit">
</form>
{% endblock content %}

matkul/templates/matkul/matkul_details.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Detail {{matkul.kode}}</title>
{% endblock meta %}

{% block content %}
<a href="/matkul"><button>Kembali</button></a>
<table>
    <tbody>
        <tr><th style="text-align: left;">Kode</th><td>{{matkul.kode}}</td></tr>
        <tr><th style="text-align: left;">Mata Kuliah</th><td>{{matkul.nama}}</td></tr>
        <tr><th style="text-align: left;">Dosen Pengajar</th><td>{{matkul.dosen}}</td></tr>
        <tr><th style="text-align: left;">Jumlah SKS</th><td>{{matkul.sks}}</td></tr>
        <tr><th style="text-align: left;">Deskripsi</th><td>{{matkul.deskripsi}}</td></tr>
    </tbody>
</table>
<a href="{% url 'matkul:delete' matkul.id %}"><button>Hapus matkul</button></a>
{% endblock content %}

story6/templates/story6/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 6</title>
{% endblock meta %}

{% block content %}
<p>Belum kelar kak HTML nya pas deadline :'), sorry</p>
<p>Baru kelar tests, models, forms</p>
{% endblock content %}

story7/templates/story7/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'story7/css/style.css' %}">
    <script type="text/javascript" src="{% static 'story7/js/script.js' %}"></script>
    
    <title>Story 7</title>
{% endblock meta %}

{% block content %}
    <h1 class="page-title">Story 7: Accordion</h1>
    <div class="page-content">
        <div class="element">
            <button class="accordion" id="acr1"><span>
            <kbd class="move-up up1" style="color:blue;">Up</kbd> 
            <kbd class="move-down down1" style="color: red;">Down</kbd>
            </span>Aktivitas</button>

            <div class="panel" id="tab1">
                <dl class="card-body">
                    <p class="card-text">1. Tidur</p>
                    <p class="card-text">2. Makan</p>
                    <p class="card-text">3. Kuliah</p>
                </dl>
            </div>
        </div>

        <div class="element">
            <button class="accordion" id="acr2"><span>
            <kbd class="move-up up1" style="color:blue;">Up</kbd> 
            <kbd class="move-down down1" style="color: red;">Down</kbd>
            </span>Pengalaman</button>
            
            <div class="panel" id="tab2">
                <div class="card-body">
                    <h5 class="card-title">1. Educare 2020)</h5>
                    <p class="card-text">Staff of TOEFL</p>
                    <p class="card-text">note : dibatalkan karena pandemi :(</p>
                    <h5 class="card-title">2. KOMPI UI (Komunitas Mahasiswa Pati UI)</h5>
                    <p class="card-text">Anggota</p>
                </div>
            </div>
        </div>

        <div class="element">
            <button class="accordion" id="acr3"><span>
            <kbd class="move-up up1" style="color:blue;">Up</kbd> 
            <kbd class="move-down down1" style="color: red;">Down</kbd>
            </span>Prestasi</button>
            
            <div class="panel" id="tab3">
                <div class="card-body">
                    <p class="card-text">Juara 1 lomba ga ngapa-ngapain</p>
                </div>
            </div>
        </div>

        <div class="element">
            <button class="accordion" id="acr4"><span>
            <kbd class="move-up up1" style="color:blue;">Up</kbd> 
            <kbd class="move-down down1" style="color: red;">Down</kbd>
            </span>Hobi</button>

            <div class="panel" id="tab4">
                <div class="card-body">
                    <p class="card-text">Menunda tugas sampai <i>deadline</i></p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

story8/templates/story8/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'story8/css/style.css' %}">
    <script type="text/javascript" src="{% static 'story8/js/script.js' %}"></script>
    
    <title>Story 8</title>
{% endblock meta %}

{% block content %}
<div class="container story-8">
    <h1 class="page-title">Story 8: AJAX</h1>
    <input class="form-control form-control-lg" id="keyword" placeholder="Masukkan judul buku">

    <table class="table" id="list-buku">
    </table>
</div>
{% endblock content %}

story9/templates/story9/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'story9/css/style.css' %}">
    
    <title>Story 9</title>
{% endblock meta %}

{% block content %}

<div class="container story-9">
    <h1 class="page-title">Story 9: Authentication</h1>

    {% if request.user.is_authenticated %}
        <h1 class="text-center title">Selamat datang, {{ user.get_username }}!</h1>
        <h1 class="text-center title">Terima kasih sudah membuat akun :)</h1>
    {% else %}
        <h1 class="text-center title">Selamat datang di story terakhir saya</h1>
    {% endif %}

    <div class="fluid-container mycontainer">
        <div class ="row justify-content-center">
            {% if user.is_anonymous %}
            <a href="{% url 'story9:signup' %}" class="btn btn-dark  btn-lg mx-2" role="button">Sign Up</a>
            <a href="{% url 'story9:login' %}" class="btn btn-light btn-lg mx-2" role="button">Login</a>
            {% else %}
            <a href="{% url 'story9:logout' %}" class="btn btn-danger btn-lg mx-2" role="button">Logout</a>
            {% endif %}
            
        </div>
    </div>
</div>    

{% endblock content %}

story9/templates/story9/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'story9/css/style.css' %}">
    
    <title>Story 9 Login</title>
{% endblock meta %}

{% block content %}

    {% if error %}
        <script>
            window.alert("Username atau Password salah");
        </script>
    {% endif %}
    
    <div class="fluid-container mycontainer">
        <div class="login-dark">
            <form method="post">
                {% csrf_token %}
                <h2 class="text-center">Login</h2>
                <div class="form-group"><input class="form-control" type="text" name="username" placeholder="Username"></div>
                <div class="form-group"><input class="form-control" type="password" name="password" placeholder="Password"></div>
                <div class="form-group"><button class="btn btn-primary btn-block" type="submit">Login</button></div>
                <p class="text-center">Don't have an account? <a href="{% url 'story9:signup' %}">Sign Up</a></p>
                <!-- <a href="{% url 'story9:signup' %}" class="btn btn-light btn-block" role="button">Sign Up</a> -->
            </form>
        </div>
    </div>    

{% endblock content %}

story9/templates/story9/signup.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'story9/css/style.css' %}">
    
    <title>Story 9 Sign Up</title>
{% endblock meta %}

{% block content %}

    {% if error %}
        <script>
            window.alert("Username sudah ada");
        </script>
    {% endif %}

    <div class="fluid-container mycontainer">
        <div class="login-dark">
            <form method="post">
                {% csrf_token %}
                <h2 class="text-center">Sign Up</h2>
                <div class="form-group"><input class="form-control" type="text" name="username" placeholder="Username"></div>
                <div class="form-group"><input class="form-control" type="password" name="password" placeholder="Password"></div>
                <div class="form-group"><button class="btn btn-primary btn-block" type="submit">Sign Up</button></div>
                <p class="text-center">Already have an account? <a href="{% url 'story9:login' %}">Login</a></p>
            </form>
        </div>
    </div>    

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <div class="topnav">
    <a class="active" href="/">Home</a>
    <a href="/story1">Story1</a>
    <a href="/story3">Story3</a>
    <a href="/matkul">Mata Kuliah</a>
    <a href="/story7">Story7</a>
    <a href="/story8">Story8</a>
    <a href="/story9">Story9</a>
  </div>
  {% block content %}
  {% endblock content %}
  <div class="footer">
    <p id="footer-text">&copy; 2020 Anis Farhan Itsnaini</p>
  </div>
</body>

</html>